// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (only share minimum)
const name = require('./04-names')
const sayHi = require('./05-utils')
const data = require('./06-alternative-flavor')
const addValues = require('./07-mind-grenade')
sayHi('susan')
sayHi(name.person1)
sayHi(name.person2)
console.log(data.singlePerson)
addValues.addi(5,10)